name: 'Saplings - Media'
description: 'Configures media best practices for modern Drupal.'
type: 'Site'
recipes:
  - imagemagick-configuration
install:
  # Core modules
  - file
  - image
  - media
  - media_library
  - path
  - views
  # Contrib modules
  - entity_browser
  - entity_browser_entity_form
  - inline_entity_form
  - media_library_edit
config:
  import:
    # Core.
    image: '*'
    media: '*'
    media_library: '*'
    views: '*'
