name: 'Saplings - Media'
description: 'Configures media best practices for modern Drupal.'
type: 'Site'
recipes: 
  - imagemagick-configuration
  - remote-video-youtube-lite
install:
  # Core modules
  - file
  - image
  - media
  - media_library
  - path
  - responsive_image
  - views
  # Contrib modules
  - entity_browser
  - entity_browser_entity_form
  - focal_point
  - inline_entity_form
  - media_library_edit
  - nomarkup
  - saplings_custom
config:
  import:
    # Core.
    image: '*'
    media: '*'
    media_library: '*'
    views: '*'
